---
# tasks file for mysql_db
    - name: Install and Configure Database
      apt:
        name:
        - mysql-server
        - mysql-client
        state: present

#    - name: Start MySQL Service
#      service:
#        name: mysql
#        state: started

    - name: "Start DB Sevice"
      shell: service mysql start
      become: yes

    - name: Create database user
      mysql_user:
       name: db_user
       password: password
       login_unix_socket: /var/run/mysqld/mysqld.sock
       priv: '*.*:ALL'
       host: '%'
       state: present
      become: yes

    - name: Create database
      mysql_db:
        login_user: "{{ db_user }}"
        login_password:  "{{ db_user_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ db_name }}"
